### ISSUE TITLE
App Architecture

### ISSUE THREAD

**Issue by Redmega** [Lordoomer/dwarf-fort-bank#1]
If you're willing, I think we'd do better to use a server framework that will help keep the frontend and backend organized.

I have a lot of experience with Next.js and React.js for the front end, but we can theoretically use any frameworks you are familiar with.

Generally speaking you also will want to commit the `package.json` and lock files so that everyone working on the project can replicate the same `node_modules` and run the application. If we convert to Next.js, Express, or whatever other backend framework we can restructure the project then.

From your readme, re: `formidable`, according to their docs you should install `formidable@canary` as the previous versions are deprecated. v2 (which lives on the `@canary` tag) is compatible with all the latest node.js versions, so no need to use a legacy `0.x` version of it.

Just out of curiousity, what kind of experience do you have with development? You definitely know your stuff but you mentioned on reddit that you were rusty.

**Comment by Lordoomer** [comment]
I only have an incomplete college degree in Multimedia Integration. My only experience is working on my own personal projects, both of which are very incomplete video games made with html , javascript and nodejs because I wanted my games to be multiplayer so I needed socket.io.
